[package]
name = "internet-15-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
dotenv = "0.15.0"
libp2p = "0.55.0"
rand = "0.9.0"
serde = "1.0.219"
serde_json = "1.0.140"
sha2 = "0.10.8"
sqlx = "0.8.3"
tokio = "1.44.0"
